spring:
  application:
    name: kafka-producer
  # kafka producer configuration:
  kafka:
    topic: test-topic
    producer:
      # The Kafka server addresses to connect to
      bootstrap-servers: localhost:9092
      # Serializer class for key that implements the org.apache.kafka.common.serialization.Serializer interface
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Serializer class for value that implements the org.apache.kafka.common.serialization.Serializer interface
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # The number of acknowledgments the producer requires the leader to have received before considering a request complete
#      acks: all
      # Setting a value greater than zero will cause the client to resend any record whose send fails with a potentially transient error
#      retries: 0
#      # The producer will attempt to batch records together into fewer requests whenever multiple records are being sent to the same partition
#      batch-size: 16384
#      # The producer groups together any records that arrive in between request transmissions into a single batched request
#      linger-ms: 1
#      # The total bytes of memory the producer can use to buffer records waiting to be sent to the server
#      buffer-memory: 33554432
#      # The configuration controls how long the producer will block when calling send() if the buffer is full
#      max-block-ms: 5000
#      # The maximum number of unacknowledged requests the client will send on a single connection before blocking
#      max-in-flight-requests-per-connection: 5
#      # The compression type for all data generated by the producer
#      compression-type: none
      # The ID to pass to the server when making requests
      # client-id: kafka-producer
      # When set to true, the producer will ensure that exactly one copy of each message is written in the stream
      # enable-idempotence: false
      # A list of classes to use as interceptors
      # interceptor-classes: com.example.kafka.producer.interceptor.ProducerInterceptorImpl